// Inquiry
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAILED = "CREATE_FAILED";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
export const DELETE_FAILED = "DELETE_FAILED";
export const ASSIGN_SUCCESS = "ASSIGN_SUCCESS";
export const ASSIGN_FAILED = "ASSIGN_FAILED";

//Application
export const APPLICATION_SUCCESS = "APPLICATION_SUCCESS";
export const APPLICATION_FAILED = "APPLICATION_FAILED";

// Register Staff

export const CREATE_ACCOUNT_STAFF_SUCCESS = "CREATE_ACCOUNT_STAFF_SUCCESS";
export const CREATE_ACCOUNT_STAFF_FAILED = "CREATE_ACCOUNT_STAFF_FAILED";

//Register Customer
export const CREATE_ACCOUNT_CUSTOMER_SUCCESS =
  "CREATE_ACCOUNT_CUSTOMER_SUCCESS";
export const CREATE_ACCOUNT_CUSTOMER_FAILED = "CREATE_ACCOUNT_CUSTOMER_FAILED";

//activate account
export const ACTIVATE_ACCOUNT_SUCCESS = "ACTIVATE_ACCOUNT_SUCCESS";
export const ACTIVATE_ACCOUNT_FAILED = "ACTIVATE_ACCOUNT_FAILED";

//authentication
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const AUTHENTICATION_SUCCCESS = "AUTHENTICATION_SUCCCESS";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILED = "LOAD_USER_FAILED";

//password configurations

export const PASSWORD_RESET_SEND_EMAIL_SUCCESS =
  "PASSWORD_RESET_SEND_EMAIL_SUCCESS";
export const PASSWORD_RESET_SEND_EMAIL_FAILED =
  "PASSWORD_RESET_SEND_EMAIL_FAILED";

export const PASSWORD_RESET_URL_SUCCESS = "PASSWORD_RESET_URL_SUCCESS";
export const PASSWORD_RESET_URL_FAILED = "PASSWORD_RESET_URL_FAILED";

//customer
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILED = "UPDATE_CUSTOMER_FAILED";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const UPDATE_RESEVATIONDETAILS_SUCCESS =
  "UPDATE_RESEVATIONDETAILS_SUCCESS";
export const UPDATE_RESEVATIONDETAILS_FAILED =
  "UPDATE_RESEVATIONDETAILS_FAILED";
export const UPLOAD_REQ_SUCCESS = "UPLOAD_REQ_SUCCESS";
export const UPLOAD_REQ_FAILED = "UPLOAD_REQ_FAILED";
export const UPLOAD_ID_SUCCESS = "UPLOAD_ID_SUCCESS";
export const UPLOAD_ID_FAILED = "UPLOAD_ID_FAILED";
export const UPLOAD_DELETE_SUCCESS = "UPLOAD_DELETE_SUCCESS";
export const UPLOAD_DELETE_FAILED = "UPLOAD_DELETE_FAILED";
export const ADD_IN_HOUSE_SUCCESS = "ADD_IN_HOUSE_SUCCESS";
export const ADD_IN_HOUSE_FAILED = "ADD_IN_HOUSE_FAILED";
export const UPDATE_IN_HOUSE_SUCCESS = "UPDATE_IN_HOUSE_SUCCESS";
export const UPDATE_IN_HOUSE_FAILED = "UPDATE_IN_HOUSE_FAILED";
export const DELETE_IN_HOUSE_SUCCESS = "DELETE_IN_HOUSE_SUCCESS";
export const DELETE_IN_HOUSE_FAILED = "DELETE_IN_HOUSE_FAILED";

//Docs
export const UPDATE_DOCS_STATUS_SUCCESS = "UPDATE_DOCS_STATUS_SUCCESS";
export const UPDATE_DOCS_STATUS_FAILED = "UPDATE_DOCS_STATUS_FAILED";

//employee
export const UPDATE_EMPLOYEE_PROFILE_SUCCESS =
  "UPDATE_EMPLOYEE_PROFILE_SUCCESS";
export const UPDATE_EMPLOYEE_PROFILE_FAILED = "UPDATE_EMPLOYEE_PROFILE_FAILED";
export const DELETE_EMPLOYEE_PROFILE_SUCCESS =
  "DELETE_EMPLOYEE_PROFILE_SUCCESS";
export const DELETE_EMPLOYEE_PROFILE_FAILED = "DELETE_EMPLOYEE_PROFILE_FAILED";
export const COMPANY_DOCS_SUCCESS = "COMPANY_DOCS_SUCCESS";
export const COMPANY_DOCS_FAILED = "COMPANY_DOCS_FAILED";
export const UPDATE_COMPANY_DOCS_SUCCESS = "UPDATE_COMPANY_DOCS_SUCCESS";
export const UPDATE_COMPANY_DOCS_FAILED = "UPDATE_COMPANY_DOCS_FAILED";
export const DELETE_COMPANY_DOCS_SUCCESS = "DELETE_COMPANY_DOCS_SUCCESS";
export const DELETE_COMPANY_DOCS_FAILED = "DELETE_COMPANY_DOCS_FAILED";
export const UPDATE_EMPLOYEE_INFO_SUCCESS = "UPDATE_EMPLOYEE_INFO_SUCCESS";
export const UPDATE_EMPLOYEE_INFO_FAILED = "UPDATE_EMPLOYEE_INFO_FAILED";
// update user profile

export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";

// Customer payments

export const CUSTOMER_PAYING_SUCCESS = "CUSTOMER_PAYING_SUCCESS";
export const CUSTOMER_PAYING_FAILED = "CUSTOMER_PAYING_FAILED";
export const PAYMENT_STATUS_SUCCESS = " PAYMENT_STATUS_SUCCESS";
export const PAYMENT_STATUS_FAILED = " PAYMENT_STATUS_FAILED";
export const UPDATE_PAYMENT_STATUS_SUCCESS = " UPDATE_PAYMENT_STATUS_SUCCESS";
export const UPDATE_PAYMENT_STATUS_FAILED = " UPDATE_PAYMENT_STATUS_FAILED";

//Labels
export const GET_ALL_LABELS = "GET_ALL_LABELS";
export const LABEL_CREATED_SUCCESS = "LABEL_CREATED_SUCCESS";
export const LABEL_CREATED_FAILED = "LABEL_CREATED_FAILED";
export const DELETE_LABEL_SUCCESS = "DELETE_LABEL_SUCCESS";
export const DELETE_LABEL_FAILED = "DELETE_LABEL_FAILED";

//Tasks

export const GET_ALL_TASKS = "GET_ALL_TASKS";
export const TASKS_UPDATE_SUCCESS = "TASKS_UPDATE_SUCCESS";
export const TASKS_UPDATE_FAILED = "TASKS_UPDATE_FAILED";
export const TASKS_CREATED_SUCCESS = "TASKS_CREATED_SUCCESS";
export const TASKS_CREATED_FAILED = "TASKS_CREATED_FAILED";
export const TASK_DELETED_SUCCESS = "TASK_DELETED_SUCCESS";
export const TASK_DELETED_FAILED = "TASK_DELETED_FAILED";
export const TASKS_ORDER_SUCCESS = "TASKS_ORDER_SUCCESS";
export const TASKS_ORDER_FAILED = "TASKS_ORDER_FAILED";

export const UPDATE_TASK_ONE_SUCCESS = "UPDATE_TASK_ONE_SUCCESS";
export const UPDATE_TASK_ONE_FAILED = "UPDATE_TASK_ONE_FAILED";

//Application

export const DELETE_APPLICATION_SUCCESS = "DELETE_APPLICATION_SUCCESS";
export const DELETE_APPLICATION_FAILED = "DELETE_APPLICATION_FAILED";
export const UPDATE_APPLICATION_STATUS_SUCCESS =
  "UPDATE_APPLICATION_STATUS_SUCCESS";
export const UPDATE_APPLICATION_STATUS_FAILED =
  "UPDATE_APPLICATION_STATUS_FAILED";

export const ADD_CUSTOMER_LOGS_SUCCESS = "ADD_CUSTOMER_LOGS_SUCCESS";
export const ADD_CUSTOMER_LOGS_FAILED = "ADD_CUSTOMER_LOGS_FAILED";
export const DELETE_CUSTOMER_LOGS_SUCCESS = "DELETE_CUSTOMER_LOGS_SUCCESS";
export const DELETE_CUSTOMER_LOGS_FAILED = "DELETE_CUSTOMER_LOGS_FAILED";

export const GET_CUSTOMER_LOGS_SUCCESS = "GET_CUSTOMER_LOGS_SUCCESS";
export const GET_CUSTOMER_LOGS_FAILED = "GET_CUSTOMER_LOGS_FAILED";

// PROPERTY
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY_SUCCESS";
export const ADD_PROPERTY_FAILED = "ADD_PROPERTY_FAILED";
export const DELETE_PROPERTY_SUCCESS = "DELETE_PROPERTY_SUCCESS";
export const DELETE_PROPERTY_FAILED = "DELETE_PROPERTY_FAILED";
export const UPDATE_PROPERTY_SUCCESS = "UPDATE_PROPERTY_SUCCESS";
export const UPDATE_PROPERTY_FAILED = "UPDATE_PROPERTY_FAILED";
export const IMAGE_PROPERTY_SUCCESS = "IMAGE_PROPERTY_SUCCESS";
export const IMAGE_PROPERTY_FAILED = "IMAGE_PROPERTY_FAILED";

//Chat

export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";
export const ADD_MESSAGE_FAILED = "ADD_MESSAGE_FAILED";
export const ADD_CONVO_SUCCESS = "ADD_CONVO_SUCCESS";
export const ADD_CONVO_FAILED = "ADD_CONVO_FAILED";

// Notifications

export const UPDATE_TO_SEEN_SUCCESS = "UPDATE_TO_SEEN_SUCCESS";
export const UPDATE_TO_SEEN_FAILED = "UPDATE_TO_SEEN_FAILED";

export const UPDATE_TO_SAVED_SUCCESS = "UPDATE_TO_SAVED_SUCCESS";
export const UPDATE_TO_SAVED_FAILED = "UPDATE_TO_SAVED_FAILED";

// Search Features

export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILED = "SEARCH_FAILED";

// Send Email

export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_FAILED = "INVOICE_FAILED";

export const UPDATE_MESSAGE_SEEN_SUCCESS = "UPDATE_MESSAGE_SEEN_SUCCESS";
export const UPDATE_MESSAGE_SEEN_FAILED = "UPDATE_MESSAGE_SEEN_FAILED";

export const PROOF_SUCCESS = "PROOF_SUCCESS";
export const PROOF_FAILED = "PROOF_FAILED";

export const SEND_CANCEL_SUCCESS = "SEND_CANCEL_SUCCESS";
export const SEND_CANCEL_FAILED = "SEND_CANCEL_FAILED";
